# - Find kerberos
# Find the native KERBEROS includes and library
#
#  KERBEROS_INCLUDE_DIRS - where to find krb5.h, etc.
#  KERBEROS_LIBRARIES    - List of libraries when using krb5.
#  KERBEROS_FOUND        - True if krb5 found.

IF (KERBEROS_INCLUDE_DIRS)
  # Already in cache, be silent
  SET(KERBEROS_FIND_QUIETLY TRUE)
ENDIF (KERBEROS_INCLUDE_DIRS)

FIND_PATH(KERBEROS_INCLUDE_DIR krb5.h)

FIND_LIBRARY(KERBEROS_LIBRARIES NAMES krb5)
FIND_LIBRARY(KERBEROS_CRYPTO_LIBRARIES NAMES k5crypto)
FIND_LIBRARY(KERBEROS_COM_ERR_LIBRARIES NAMES com_err)
FIND_LIBRARY(KERBEROS_SUPPORT_LIBRARIES NAMES krb5support)
SET(KERBEROS_LIBRARIES ${KERBEROS_LIBRARIES} 
    ${KERBEROS_CRYPTO_LIBRARIES} ${KERBEROS_COM_ERR_LIBRARIES} ${KERBEROS_SUPPORT_LIBRARIES})
SET(KERBEROS_GSSAPI_NAMES gssapi_krb5 gssapi)
FIND_LIBRARY(KERBEROS_GSSAPI_LIBRARY NAMES ${KERBEROS_GSSAPI_NAMES})
SET(KERBEROS_LIBRARIES ${KERBEROS_LIBRARIES} ${KERBEROS_GSSAPI_LIBRARY})

# handle the QUIETLY and REQUIRED arguments and set KERBEROS_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(KERBEROS DEFAULT_MSG KERBEROS_LIBRARIES KERBEROS_INCLUDE_DIR)

MARK_AS_ADVANCED(KERBEROS_LIBRARIES KERBEROS_INCLUDE_DIRS)
